spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 1234

graphql:
  tools:

  playground:
    enabled: true
  altair:
    enabled: true
  voyager:
    enabled: true
  graphiql:
    enabled: true

